### ISSUE TITLE
Doesn't work with Typescript

### ISSUE THREAD

**Issue by muuhoffman** [ksoichiro/rehype-img-size#3]
Getting the error below when used in the method described by this blog: https://ironeko.com/posts/how-to-use-next-js-image-with-markdown-or-mdx 

```
error - TypeError: resolvePath is not a function
    at visitor (/Users/matthoffman/code/possible-place/node_modules/rehype-image-size/index.js:17:28)
    at overload (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit/index.js:27:12)
    at visit (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit-parents/index.js:56:27)
    at visit (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit-parents/index.js:67:75)
    at visit (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit-parents/index.js:67:75)
    at visitParents (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit-parents/index.js:29:26)
    at visit (/Users/matthoffman/code/possible-place/node_modules/unist-util-visit/index.js:22:3)
    at transform (/Users/matthoffman/code/possible-place/node_modules/rehype-image-size/index.js:23:5)
    at wrapped (/Users/matthoffman/code/possible-place/node_modules/trough/wrap.js:25:19)
    at next (/Users/matthoffman/code/possible-place/node_modules/trough/index.js:57:24) {
  page: '/blog/[slug]'
}
```

**Comment by crutchcorn** [comment]
I will be making a PR to add TS typings soon
